services:
#    admin.example:
#        class: AdminBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    admin.admin.store:
        class: AdminBundle\Admin\StoreAdmin
        arguments: [~, AppBundle\Entity\Store, AdminBundle:StoreAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Store, on_top: true}
        calls:
            - [addChild, ['@admin.admin.product']]

    admin.admin.product:
        class: AdminBundle\Admin\ProductAdmin
        arguments: [~, AppBundle\Entity\Product, AdminBundle:ProductAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Product, show_in_dashboard: false}
