<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;

use AppBundle\Entity\Store;
use Doctrine\Common\Collections\ArrayCollection;
use Sonata\UserBundle\Entity\BaseUser as BaseUser;

/**
 * This file has been generated by the Sonata EasyExtends bundle.
 *
 * @link https://sonata-project.org/bundles/easy-extends
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class User extends BaseUser
{
    /**
     * @var int $id
     */
    protected $id;

    /**
     * Get id
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @var Store []| ArrayCollection
     */
    protected $stores;

    /**
     * @return \AppBundle\Entity\Store[]|ArrayCollection
     */
    public function getStores()
    {
        return $this->stores;
    }

    /**
     * @param \AppBundle\Entity\Store[]|ArrayCollection $stores
     * @return User
     */
    public function setStores($stores)
    {
        $this->stores = $stores;
        return $this;
    }

    /**
     * @param Store $store
     * @return $this
     */
    public function addStore(Store $store)
    {
        $this->stores->add($store);

        return $this;
    }
}
